### ISSUE TITLE
[Feature Request] Add a PR Preview Bot for GitRoll Profile Card Rendering

### ISSUE THREAD

**Issue by 1chooo** [gitroll-dev/gitroll-profile-card#2]
Currently, when a pull request (PR) is submitted, we cannot directly view how the GitRoll Profile Card is rendered. Would it be possible to design a bot that automatically deploys the rendered result upon receiving a PR? This would help avoid cases where contributors do not provide sufficient explanation in their PRs.

**Reference:**  
- [GitHub Readme Stats Repository](https://github.com/anuraghazra/github-readme-stats) This repository deploys styles automatically for every PR. For example, here is a PR I submitted previously: [[Example PR](https://github.com/anuraghazra/github-readme-stats/pull/3670)] https://github.com/anuraghazra/github-readme-stats/pull/3670.

### Screenshots

<img width="1280" alt="Screenshot 2024-11-23 at 1 01 24 AM" src="https://github.com/user-attachments/assets/d6338e3d-0dd2-4faa-a1d9-abfe58155398">

<img width="1280" alt="Screenshot 2024-11-23 at 1 01 29 AM" src="https://github.com/user-attachments/assets/1b9c1780-9d77-4943-99d5-3e2768cde043">

**Comment by JacobLinCool** [comment]
We have added the preview bot. Please check out [PR #6](https://github.com/gitroll-dev/gitroll-profile-card/pull/6) to see the effect.
Feel free to close the issue or add a comment!
